### ISSUE TITLE
Calculator demo does not work on Firefox

### ISSUE THREAD

**Issue by Chaz6** [roozbehid/WasmWinforms#1]
Using Firefox on Windows 10, the calculator demo does not work and logs this error to the console:-

```
RangeError: bad Memory initial size mono.js:1181:26
<anonymous> https://webassembly.z19.web.core.windows.net/Calculator/mono.js:1181:26
```

**Comment by chris-morgan** [comment]
```js
var TOTAL_MEMORY = Module["TOTAL_MEMORY"] || 1258291200;
```

Module.TOTAL_MEMORY is undefined, so it asks for about 1.25GB.

**Comment by roozbehid-ic** [comment]
I did compile it with -s TOTAL_MEMORY=1000MB, so maybe thats how emscripten generates that code...

**Comment by roozbehid** [comment]
Rerun it again. I fixed many memory leak bugs...so maybe now it works! reopen if you still have issues
