### ISSUE TITLE
~RunWrapper caused an exception:System.ArgumentException: Illegal characters in path.

### ISSUE THREAD

**Issue by sengiv** [roozbehid/WasmWinforms#13]
Any suggestion to fix this error when compiling to WasmRel?

**Comment by roozbehid** [comment]
I need more information than this.

**Comment by roozbehid** [comment]
what os are you using?more of error message and how are you doing it

**Comment by sengiv** [comment]
Windows 10 Home, Visual Studio 2019 Ent

**Comment by sengiv** [comment]
![image](https://user-images.githubusercontent.com/43817262/76482099-2dfcf280-644e-11ea-8d05-10f0bb30a84a.png)
I hope the screen shot helps, Release x86 builds fine, problems is only when I try to build WasmRel or WasmDbg targets.

**Comment by roozbehid** [comment]
Can you switch to output so I see more messages. Also what is your project located at? Full path of it

**Comment by sengiv** [comment]
Project path : D:\Repos\WasmWinforms-prod\WasmWinforms
[error-output.txt](https://github.com/roozbehid/WasmWinforms/files/4322052/error-output.txt)

**Comment by roozbehid** [comment]
Seems like some character in your path is off...
Maybe if you can download https://github.com/roozbehid/dotnet-vcxproj and build it in Debug it, you can find out why.

On Properties of GCCBuild->Debug put executable as 
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe" (or your msbuild location for your visual studio)

Applications arguments:
D:\Repos\WasmWinforms-prod\WasmWinforms\WasmWinforms.sln /p:Configuration=WasmRel /p:Platform=x86 /bl 

Working directory:
it should be your GCCBuild

Environment variables:

VCTargetsPath  .

First, before debugging, build GCCBuild in Debug mode, then copy *.dll and *.pdb into
C:\Users\Raynon\.nuget\packages\gccbuildtargets\1.19.325.5 (overwrite dlls there)

Now debugging it you should get the exception and see why you are getting it.
Also you get another exception in catch of CCompilerTask.cs:296

Let me know if you found something and thanks

**Comment by roozbehid** [comment]
if you open a cmd.exe can you type gcc and get results?
Also if you dont want to go into debugging gccbuild. send me another output with MSBuild verbosity set to detailed.

You should go to Tools->Options->Project and Solutions->Build and Run->MSBuild project build output verbosity:Detailed

You can also use msbuild same way as described above with /bl option. That option would generate a binary log output which has everything to debug what goes wrong during compilation

**Comment by sengiv** [comment]
Thanks for your quick reply. I had completely forgotten about installing gcc.
After installing gcc, the errors have changed a little.
I'm new to compiling c++/c & your help with interpreting the outputs would be real nice. Will post the outputs here soon.

**Comment by sengiv** [comment]
[error-output2.txt](https://github.com/roozbehid/WasmWinforms/files/4328075/error-output2.txt)
attached is build output with verbosity set to detailed, pls let me know if you find anything

**Comment by sengiv** [comment]
![image](https://user-images.githubusercontent.com/43817262/76597433-66c6c580-653b-11ea-869b-9ecea69dab27.png)
@roozbehid I suspect this is the issue, but I don't know how to fix it. Any ideas?

**Comment by roozbehid** [comment]
I dont think that is an issue.
Take a look at ```D:\emsdk-master\upstream\emscripten\emcc.BAT``` and see if that file is ok and runs well!

The error you see for the most part can be just ignored. emcc seems to be working fine too as it is also compiling. That error message is generating at the end during cleanup phase which is totally fine to ignore.

Try to build projects one by one and see if you find anything interesting. 
Also do this in your cmd ```echo %PATH%``` and see if you see something wrong with any directories in your path.

**Comment by sengiv** [comment]
emcc.BAT is working fine, but the file is named with lower case ".bat",
but I don't think it would effect, in echo %PATH% all looks good

my major target atm is to rebuild mono.wasm file, I've made changes in drive.c and would like to see how it works. Is there any other way you can recommend to build it?

I'll try building projects one by one and see if I can find anything, thanks

**Comment by evilguest** [comment]
I have a similar issue. Compiling a very simple .vcxproj with configuration named "GCC".
Here is an output:
```
1>C:\Users\azlygostev.SWSOFT\.nuget\packages\gccbuildtargets\1.19.325.5\build\Microsoft.Cpp.targets(173,5): error : ~RunWrapper caused an exception:System.ArgumentException: Illegal characters in path.
1>C:\Users\azlygostev.SWSOFT\.nuget\packages\gccbuildtargets\1.19.325.5\build\Microsoft.Cpp.targets(173,5): error :    at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
1>C:\Users\azlygostev.SWSOFT\.nuget\packages\gccbuildtargets\1.19.325.5\build\Microsoft.Cpp.targets(173,5): error :    at System.IO.Path.GetExtension(String path)
1>C:\Users\azlygostev.SWSOFT\.nuget\packages\gccbuildtargets\1.19.325.5\build\Microsoft.Cpp.targets(173,5): error :    at GCCBuild.RunWrapper.Dispose() in D:\a\1\s\GCCBuild\RunWrapper.cs:line 44
```

**Comment by sengiv** [comment]
@evilguest a few things you can try :

- copy files that didn't compile directly from "https://webassembly.z19.web.core.windows.net/" to your build directory
- gcc is installed & working from CMD
- changing build configuration to only build for x86
- skip building "mono.wasm" (or only build what you absolutely need)

I've mostly forgotten how this works, but if I remember correctly you don't need to build your project to wasm.
I think this is what worked for me.
1. copy all the files from the demo site,
2. add in your dll into same folder, 
3. modify mono-config.js to reference you project's dll

hope it helps

PS: take a look at this guide, it helped me
https://itnext.io/run-c-natively-in-the-browser-through-the-web-assembly-via-mono-wasm-60f3d55dd05a

**Comment by evilguest** [comment]
Sorry for a misleading location - my project has nothing to do with wasm. I am building a simple C++ dynamic link library for x64. Project works fine when built from VS or msbuild in the "regular" configurations; however, the compilation fails with the error message I've quoted when I try to choose the GCC configuration.
