### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ustun** [roozbehid/WasmWinforms#2]
README says the following: "Maybe call it some useless technology..."

This is definitely not true. Lots of businesses run on old winforms code, which, if converted to web app could be a real benefit. 

I know enterprise companies trying to do such transformations.

**Comment by roozbehid-ic** [comment]
Yeah. thanks I will update the readme file. good points

**Comment by ustun** [comment]
keep going, this might be commercialized perhaps
