### ISSUE TITLE
System.Drawing.New

### ISSUE THREAD

**Issue by gsmental** [roozbehid/WasmWinforms#4]
Severity	Code	Description	Project	File	Line	Suppression State
Error		
Unhandled Exception: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Drawing.New, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Driver.Import(String ra, AssemblyKind kind)
   at Driver.Run(String[] args)
   at Driver.Main(String[] args)
	ConsoleApp2	C:\Users\hp\.nuget\packages\winforms.wasm\1.0.0.33\build\netstandard2.0\Winforms.Wasm.targets	13

**Comment by Nunction** [comment]
@gsmental  Had the same problem, adding ```<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>``` to the csproj resolved it for me.

**Comment by roozbehid** [comment]
Yes that is what you need for now....or you can publish it I assume.
