### ISSUE TITLE
Rendering Issue After Using ComboBox or Tab

### ISSUE THREAD

**Issue by bausshf** [roozbehid/WasmWinforms#5]
When using the ComboBox or Tab the UI will render like below:

![Error](https://i.imgur.com/XV6R3Rb.png "Error")

I use Chrome as the browser.

**Comment by roozbehid** [comment]
Yeah I've seen this and right now is not much priority for me. Will work on it soon

**Comment by bausshf** [comment]
I see, thanks!

**Comment by roozbehid** [comment]
All fixed.
